[package]
name = "my_penrose"
version = "0.1.0"
authors = ["niloco"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.9.0"
penrose = "0.2"
simplelog = "0.8"
